version: '3'
services:
    php-apache2:
        image: php:7.4.3-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html:z
        links:
            - 'mysql'

    mysql:
        image: mysql        
        environment:
            TZ: "INDIA"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "sneha"
            MYSQL_USER: 'surana'
            MYSQL_PASSWORD: 'surana'
            MYSQL_DATABASE: 'details'
        ports:
            - '3306:3306'
        expose :
            - '3306'
        volumes:
            - mysql:/var/lib/mysql
            - mysql:/var/log/mysql  

volumes:
    mysql:
